// Mock data untuk demo aplikasi

import { Product, User, Vendor, Order, Review, POSItem, PPOBProduct } from '@/types';

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'buyer',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  balance: 500000,
};

export const mockProducts: Product[] = [
  {
    id: '1',
    vendorId: 'v1',
    vendorName: 'Toko Elektronik Jaya',
    name: 'Smartphone Samsung Galaxy A54',
    description: 'Smartphone dengan kamera 50MP, layar AMOLED 6.4", RAM 8GB, Storage 256GB',
    price: 4999000,
    originalPrice: 5999000,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500',
    ],
    category: 'Elektronik',
    stock: 50,
    rating: 4.8,
    reviewCount: 234,
    sold: 1250,
    isDigital: false,
    variants: [
      { id: 'v1', name: 'Warna', options: ['Hitam', 'Putih', 'Biru'] },
      { id: 'v2', name: 'Storage', options: ['128GB', '256GB'] },
    ],
  },
  {
    id: '2',
    vendorId: 'v2',
    vendorName: 'Fashion Store',
    name: 'Kaos Polos Premium Cotton',
    description: 'Kaos polos berbahan cotton combed 30s, nyaman dan adem',
    price: 75000,
    originalPrice: 100000,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    category: 'Fashion',
    stock: 200,
    rating: 4.5,
    reviewCount: 89,
    sold: 450,
    isDigital: false,
    variants: [
      { id: 'v1', name: 'Ukuran', options: ['S', 'M', 'L', 'XL', 'XXL'] },
      { id: 'v2', name: 'Warna', options: ['Hitam', 'Putih', 'Abu-abu', 'Navy'] },
    ],
  },
  {
    id: '3',
    vendorId: 'v3',
    vendorName: 'Digital Store',
    name: 'E-Book: Panduan Bisnis Online',
    description: 'Panduan lengkap memulai bisnis online dari nol hingga sukses',
    price: 99000,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500',
    category: 'Digital',
    stock: 9999,
    rating: 4.9,
    reviewCount: 567,
    sold: 3420,
    isDigital: true,
  },
  {
    id: '4',
    vendorId: 'v1',
    vendorName: 'Toko Elektronik Jaya',
    name: 'Laptop ASUS VivoBook 14',
    description: 'Laptop dengan prosesor Intel Core i5, RAM 8GB, SSD 512GB',
    price: 7999000,
    originalPrice: 9999000,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500',
    category: 'Elektronik',
    stock: 25,
    rating: 4.7,
    reviewCount: 156,
    sold: 320,
    isDigital: false,
  },
  {
    id: '5',
    vendorId: 'v4',
    vendorName: 'Rumah Buku',
    name: 'Buku: Atomic Habits',
    description: 'Buku best seller tentang membangun kebiasaan baik',
    price: 89000,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    category: 'Buku',
    stock: 100,
    rating: 4.9,
    reviewCount: 890,
    sold: 2340,
    isDigital: false,
  },
  {
    id: '6',
    vendorId: 'v2',
    vendorName: 'Fashion Store',
    name: 'Sepatu Sneakers Casual',
    description: 'Sepatu sneakers casual untuk pria dan wanita',
    price: 299000,
    originalPrice: 450000,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    category: 'Fashion',
    stock: 75,
    rating: 4.6,
    reviewCount: 234,
    sold: 890,
    isDigital: false,
  },
];

export const mockVendors: Vendor[] = [
  {
    id: 'v1',
    name: 'Toko Elektronik Jaya',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TEJ',
    description: 'Toko elektronik terpercaya sejak 2010',
    rating: 4.8,
    products: 250,
    followers: 15000,
    joinDate: '2010-05-15',
    commission: 10,
  },
  {
    id: 'v2',
    name: 'Fashion Store',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=FS',
    description: 'Fashion trendy dengan harga terjangkau',
    rating: 4.6,
    products: 450,
    followers: 25000,
    joinDate: '2015-08-20',
    commission: 15,
  },
  {
    id: 'v3',
    name: 'Digital Store',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=DS',
    description: 'Produk digital berkualitas',
    rating: 4.9,
    products: 120,
    followers: 8500,
    joinDate: '2018-03-10',
    commission: 20,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '1',
    vendorId: 'v1',
    items: [
      {
        id: '1',
        product: mockProducts[0],
        quantity: 1,
        selectedVariants: { Warna: 'Hitam', Storage: '256GB' },
      },
    ],
    total: 4999000,
    status: 'delivered',
    paymentMethod: 'Tripay - BCA Virtual Account',
    shippingAddress: 'Jl. Sudirman No. 123, Jakarta Selatan',
    trackingNumber: 'JNE123456789',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'ORD-002',
    userId: '1',
    vendorId: 'v2',
    items: [
      {
        id: '2',
        product: mockProducts[1],
        quantity: 2,
        selectedVariants: { Ukuran: 'L', Warna: 'Hitam' },
      },
    ],
    total: 150000,
    status: 'shipped',
    paymentMethod: 'COD',
    shippingAddress: 'Jl. Gatot Subroto No. 45, Jakarta Pusat',
    trackingNumber: 'SICEPAT987654321',
    createdAt: '2024-01-20T14:20:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    userId: '1',
    userName: 'Budi Santoso',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    productId: '1',
    rating: 5,
    comment: 'Produk sangat bagus, sesuai deskripsi. Pengiriman cepat!',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300'],
    createdAt: '2024-01-16T08:00:00Z',
  },
  {
    id: 'r2',
    userId: '2',
    userName: 'Siti Nurhaliza',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    productId: '1',
    rating: 4,
    comment: 'Bagus, tapi agak lama sampainya. Overall puas.',
    createdAt: '2024-01-18T15:30:00Z',
  },
];

export const mockPOSItems: POSItem[] = [
  {
    id: 'pos1',
    sku: 'BRG-001',
    name: 'Indomie Goreng',
    category: 'Makanan',
    buyPrice: 2500,
    sellPrice: 3500,
    stock: 500,
    unit: 'pcs',
  },
  {
    id: 'pos2',
    sku: 'BRG-002',
    name: 'Aqua 600ml',
    category: 'Minuman',
    buyPrice: 3000,
    sellPrice: 4000,
    stock: 300,
    unit: 'pcs',
  },
  {
    id: 'pos3',
    sku: 'BRG-003',
    name: 'Sabun Mandi Lifebuoy',
    category: 'Toiletries',
    buyPrice: 5000,
    sellPrice: 7000,
    stock: 150,
    unit: 'pcs',
  },
];

export const mockPPOBProducts: PPOBProduct[] = [
  {
    id: 'ppob1',
    category: 'pulsa',
    name: 'Pulsa Telkomsel 10.000',
    provider: 'Telkomsel',
    price: 11000,
    description: 'Pulsa reguler Telkomsel',
  },
  {
    id: 'ppob2',
    category: 'data',
    name: 'Paket Data XL 3GB',
    provider: 'XL',
    price: 25000,
    description: 'Paket internet 3GB masa aktif 30 hari',
  },
  {
    id: 'ppob3',
    category: 'pln',
    name: 'Token PLN 50.000',
    provider: 'PLN',
    price: 51000,
    description: 'Token listrik PLN',
  },
];

export const categories = [
  { id: 'elektronik', name: 'Elektronik', icon: '📱' },
  { id: 'fashion', name: 'Fashion', icon: '👕' },
  { id: 'makanan', name: 'Makanan & Minuman', icon: '🍔' },
  { id: 'buku', name: 'Buku', icon: '📚' },
  { id: 'digital', name: 'Produk Digital', icon: '💾' },
  { id: 'kesehatan', name: 'Kesehatan', icon: '💊' },
  { id: 'olahraga', name: 'Olahraga', icon: '⚽' },
  { id: 'otomotif', name: 'Otomotif', icon: '🚗' },
];
